Name:           ros-melodic-prbt-pg70-support
Version:        0.0.2
Release:        0%{?dist}
Summary:        ROS prbt_pg70_support package

Group:          Development/Libraries
License:        Apache 2.0
URL:            https://wiki.ros.org/prbt_pg70_support
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-prbt-ikfast-manipulator-plugin
Requires:       ros-melodic-prbt-moveit-config
Requires:       ros-melodic-prbt-support
Requires:       ros-melodic-schunk-description
Requires:       ros-melodic-xacro
BuildRequires:  ros-melodic-catkin

%description
PRBT support for Schunk pg70 gripper.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Fri Apr 12 2019 Alexander Gutenkunst <a.gutenkunst@pilz.de> - 0.0.2-0
- Autogenerated by Bloom

* Tue Sep 11 2018 Pilz GmbH and Co. KG <ros@pilz.de> - 0.0.1-0
- Autogenerated by Bloom

